name: Go Tests
env:
  GOPRIVATE: "github.com/Instacomm"
on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: "1.25"
    secrets:
      git-token:
        required: true
      git-user:
        required: true
jobs:
  go-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    services:
      postgres:
        image: postgres:${{ vars.TEST_POSTGRES_VERSION || 16 }}
        env:
          POSTGRES_USER: ${{ vars.TEST_DB_USERNAME || 'instacom' }}
          POSTGRES_PASSWORD: ${{ vars.TEST_DB_PASSWORD || 'instacom' }}
          POSTGRES_DB: ${{ vars.TEST_DB_NAME || 'instacom' }}
        ports:
          - ${{ vars.TEST_DB_PORT || 5432 }}:5432
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          token: ${{ secrets.git-token }}
          go-version: ${{ inputs.version }}
          cache: true
      - name: Configure Netrc
        uses: extractions/netrc@v2
        with:
          machine: github.com
          username: ${{ secrets.git-user }}
          password: ${{ secrets.git-token }}
      - name: Download dependencies
        run: go mod download
      - name: Configure application
        run: |
          cp ./.env.local.example ./.env
          cp ./config.example.yaml ./config.yaml
          go test ./...
      - name: Run tests
        run: go test ./...
