
env:
  GOPRIVATE: "github.com/govnet-*"
  OUTPUT_BIN: ${{ inputs.service }}-bin
  DOCKERHUB_REPO: ${{ vars.DOCKERHUB_ORG }}/${{ vars.DOCKERHUB_REPO }}
  DOCKERFILE_BUILDER_IMG: alpine
on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: null
      go-version:
        required: false
        type: string
        default: '1.22'
      service:
        required: true
        type: string
      service-port:
        required: false
        type: number
        default: 80
      environment: 
        required: false
        type: string
        default: ${{ vars.BUILD_ENV || 'develop' }}
      node-version: 
        required: false
        type: string
        default: ${{ vars.NODE_VERSION || 'v20.3.0' }}
      go-file:
        type: string
        default: ./main.go
      vue-dir:
        type: string
        default: web
      migration-path:
        required: false
        type: string
        default: 'sql/migrations'
    secrets: 
      git-token:
        required: true
      git-user:
        required: true
      dockerhub-token:
        required: true
      dockerhub-user:
        required: true
jobs:
  go-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Configure Netrc
      uses: extractions/netrc@v2
      with:
        machine: github.com
        username: ${{ secrets.git-user }}
        password: ${{ secrets.git-token }}
    - name: Do version preps
      run: |
        echo "GITHUB_SHA_SHORT=`git rev-parse --short ${{ github.sha }}`" >> $GITHUB_ENV
        echo "GITHUB_BRANCH_SHORT=`git branch --show-current | sed 's/\//_/g' | tr -d ' '`" >> $GITHUB_ENV
        echo "SERVICE_BUILD=`date -I`-`git rev-parse --short ${{ github.sha }}`" >> $GITHUB_ENV
        echo "GITHUB_BRANCH_SHORT=`git branch --show-current | sed 's/\//_/g' | tr -d ' '`" >> $GITHUB_ENV
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.dockerhub-user }}
        password: ${{ secrets.dockerhub-token }} 
    - name: prep directory for npm
      run: cp ${{ inputs.vue-dir }}/package*.json .
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
    - name: Download ${{ inputs.service }} npm dependencies
      run: ls -lah && cd ./${{ inputs.vue-dir }} && npm i && cd ..
    - name: Build ${{ inputs.service }} npm dependencies
      run: cd ./${{ inputs.vue-dir }} && npm run build && mv dist .. && cd .. && ls -lah
    - name: Show dist
      run: ls -lah dist
    - name: Setup go ${{ inputs.go-version }}
      uses: actions/setup-go@v5
      with:
        token: ${{ inputs.git-token }}
        go-version: ${{ inputs.go-version }}
        cache: true   
    - name: Download ${{ inputs.service }} dependencies
      run: go mod download
    - name: Build ${{ inputs.service }}
      run: |
        CGO_ENABLED=0 GO111MODULE=on GOOS=linux \
          go build -a \
          -ldflags "-s -w -X main.Release=${{ inputs.service }}-${{ env.SERVICE_BUILD }} -X main.SHA=${{ github.sha }}" \
          -installsuffix cgo -o ${{ env.OUTPUT_BIN }} ${{ inputs.go-file }}
    - name: Write Dockerfile
      run: |
        cat <<EOF > Dockerfile 
        FROM gomicro/goose:3.24.1 as gooze
        FROM ${{ env.DOCKERFILE_BUILDER_IMG }} as builder
        WORKDIR /app
        COPY dist /app/dist
        COPY ${{ env.OUTPUT_BIN }} /app
        COPY --from=gooze /bin/goose /bin/goose
        COPY ${{ inputs.migration-path }} /sql/migrations
        ENV APP_HTTP_PORT=${{ inputs.service-port }}
        ENV VERSION=${{ inputs.service }}-${{ env.GITHUB_SHA_SHORT }}
        ENV WEB_PRODUCTION_MODE=true
        ENV GO_PRODUCTION_MODE=true
        ENV SKIP_HOUSEKEEPING=true
        ENV SOURCE=github.com/${{ github.repository }}@${{ env.GITHUB_SHA_SHORT }}
        EXPOSE ${{ inputs.service-port }}
        CMD ["/app/${{ env.OUTPUT_BIN }}"]
        EOF
    - name: Docker publish ${{ inputs.service }} image to registry
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKERHUB_REPO }}:${{ github.sha }}
          ${{ env.DOCKERHUB_REPO }}:${{ inputs.version }}
          ${{ env.DOCKERHUB_REPO }}:${{ env.GITHUB_BRANCH_SHORT }}
          ${{ env.DOCKERHUB_REPO }}:${{ env.GITHUB_BRANCH_SHORT }}-${{ env.GITHUB_SHA_SHORT }}
          ${{ env.DOCKERHUB_REPO }}:${{ env.SERVICE_BUILD }}
          ${{ env.DOCKERHUB_REPO }}:${{ env.GITHUB_SHA_SHORT }}
          ${{ env.DOCKERHUB_REPO }}:latest