env:
  GOPRIVATE: "github.com/Instacomm"
  OUTPUT_BIN: ${{ inputs.service }}-bin
  DOCKERFILE_BUILDER_IMG: alpine
on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: develop
      go-version:
        required: false
        type: string
        default: "1.25"
      service:
        required: true
        type: string
      service-port:
        required: false
        type: number
        default: 80
      environment:
        required: false
        type: string
        default: ${{ vars.BUILD_ENV || 'develop' }}
      node-version:
        required: false
        type: string
        default: ${{ vars.NODE_VERSION || 'v20.3.0' }}
      go-file:
        type: string
        default: ./main.go
      vue-dir:
        type: string
        default: web
      migration-path:
        required: false
        type: string
        default: "sql/migrations"
      dispatch-workflow-url:
        required: false
        type: string
        default: ""
      docker-host:
        required: false
        type: string
        default: ${{ vars.DOCKER_REGISTRY || 'docker.registry.io' }}
    secrets:
      git-token:
        required: true
      git-user:
        required: true
      docker-token:
        required: true
      docker-user:
        required: true
jobs:
  go-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Configure Netrc
        uses: extractions/netrc@v2
        with:
          machine: github.com
          username: ${{ secrets.git-user }}
          password: ${{ secrets.git-token }}
      - name: Do version preps
        run: |
          echo "GITHUB_SHA_SHORT=`git rev-parse --short ${{ github.sha }}`" >> $GITHUB_ENV
          echo "GITHUB_BRANCH_SHORT=`git branch --show-current | sed 's/\//_/g' | tr -d ' '`" >> $GITHUB_ENV
          echo "SERVICE_BUILD=`date -I`-`git rev-parse --short ${{ github.sha }}`" >> $GITHUB_ENV
          echo "GITHUB_BRANCH_SHORT=`git branch --show-current | sed 's/\//_/g' | tr -d ' '`" >> $GITHUB_ENV
      - name: Login to Docker Reposotory (${{ inputs.docker-host }})
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.docker-host }}
          username: ${{ secrets.docker-user }}
          password: ${{ secrets.docker-token }}
      - name: prep directory for npm
        run: cp ${{ inputs.vue-dir }}/package*.json .
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm
      - name: Download ${{ inputs.service }} npm dependencies
        run: ls -lah && cd ./${{ inputs.vue-dir }} && npm i && cd ..
      - name: Build ${{ inputs.service }} npm dependencies
        run: cd ./${{ inputs.vue-dir }} && npm run build && mv dist .. && cd .. && ls -lah
      - name: Show dist
        run: ls -lah dist
      - name: Setup go ${{ inputs.go-version }}
        uses: actions/setup-go@v5
        with:
          token: ${{ inputs.git-token }}
          go-version: ${{ inputs.go-version }}
          cache: true
      - name: Download ${{ inputs.service }} dependencies
        run: go mod download
      - name: Build ${{ inputs.service }}
        run: |
          CGO_ENABLED=0 GO111MODULE=on GOOS=linux \
            go build -a \
            -ldflags "-s -w -X main.Release=${{ inputs.service }}-${{ env.SERVICE_BUILD }} -X main.SHA=${{ github.sha }}" \
            -installsuffix cgo -o ${{ env.OUTPUT_BIN }} ${{ inputs.go-file }}
      - name: Write Dockerfile
        run: |
          cat <<EOF > Dockerfile 
          FROM gomicro/goose:3.24.1 as gooze
          FROM ${{ env.DOCKERFILE_BUILDER_IMG }} as builder
          WORKDIR /app
          COPY dist /app/dist
          COPY ${{ env.OUTPUT_BIN }} /app
          COPY --from=gooze /bin/goose /bin/goose
          COPY ${{ inputs.migration-path }} /sql/migrations
          ENV APP_HTTP_PORT=${{ inputs.service-port }}
          ENV VERSION=${{ inputs.service }}-${{ env.GITHUB_SHA_SHORT }}
          ENV WEB_PRODUCTION_MODE=true
          ENV GO_PRODUCTION_MODE=true
          ENV SKIP_HOUSEKEEPING=true
          ENV GOOSE_DRIVER="postgres" 
          ENV GOOSE_DBSTRING="user=${DB_USERNAME} password=${DB_PASSWORD} host=${DB_HOST} port=${DB_PORT} dbname=${DB_DATABASE} sslmode=disable" 
          ENV SOURCE=github.com/${{ github.repository }}@${{ env.GITHUB_SHA_SHORT }}
          EXPOSE ${{ inputs.service-port }}
          CMD ["/app/${{ env.OUTPUT_BIN }}"]
          EOF
      - name: Docker publish ${{ inputs.service }} image to registry
        uses: docker/build-push-action@v5
        env:
          DOCKER_REPO: ${{ inputs.docker-host }}/${{ vars.DOCKER_ORG }}/${{ vars.DOCKER_REPO }}
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:${{ inputs.version || 'develop' }}
            ${{ env.DOCKER_REPO }}:${{ env.GITHUB_BRANCH_SHORT }}
            ${{ env.DOCKER_REPO }}:latest
      - name: Link to Deploy Workflow
        if: success() && inputs.dispatch-workflow-url != ''
        env:
          DEPLOY_URL: "${{ inputs.dispatch-workflow-url }}?query=workflow_dispatch&tag=${{ env.GITHUB_SHA_SHORT }}"
        run: |
          echo "## ðŸš€ [**Deploy this Build**](${{ env.DEPLOY_URL }})" >> $GITHUB_STEP_SUMMARY
          echo "- You will need to provide the tag (${{ env.GITHUB_SHA_SHORT }}) to deploy this version" >> $GITHUB_STEP_SUMMARY
