env:
  DOCKERFILE_BUILDER_IMG: eclipse-${{ inputs.java-distribution }}:${{ inputs.java-version }}-jdk
  DOCKERHUB_REPO: ${{ vars.DOCKERHUB_ORG }}/${{ vars.DOCKERHUB_REPO }}
  DOCKER_BUILDKIT: 1
on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: null
      java-version:
        required: false
        type: string
        default: '20'
      java-distribution:
        required: false
        type: string
        default: '${{ inputs.java-distribution }}'
      java-platform:
        required: false
        type: string
        default: 'linux/amd64'
      jre-cache:
        required: false
        type: string
        default: 'maven'
      service:
        required: true
        type: string
      service-port:
        required: false
        type: number
        default: 8080
      dockerfile-runner-img:
        required: false
        type: string
        default: 'eclipse-${{ inputs.java-distribution }}:${{ inputs.java-version }}-jre'
    secrets: 
      mvn-token:
        required: true
      mvn-user:
        required: true
      docker-token:
        required: true
      docker-user:
        required: true
jobs:
  java-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set env
      run: |
        echo "GITHUB_SHA_SHORT=`git rev-parse --short ${{ github.sha }}`" >> $GITHUB_ENV
        echo "GITHUB_BRANCH_SHORT=`git branch --show-current | sed 's/\//_/g' | tr -d ' '`" >> $GITHUB_ENV
        echo "DOCKERHUB_REPO=${{ vars.DOCKERHUB_ORG }}/$(echo ${{ vars.DOCKERHUB_REPO }} | cut -d '/' -f 2)" >> $GITHUB_ENV
        echo "SERVICE_BUILD=`date -I`-`git rev-parse --short ${{ github.sha }}`" >> $GITHUB_ENV
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.docker-user }}
        password: ${{ secrets.docker-token }} 
    - name: Setup JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        cache: ${{ inputs.jre-cache }}
    - name: Set up Maven settings.xml
      run: |
        cat <<EOF > ~/.m2/settings.xml 
        <?xml version="1.0" encoding="UTF-8"?>
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
          <activeProfiles>
              <activeProfile>github</activeProfile>
          </activeProfiles>
          <profiles>
              <profile>
                <id>github</id>
                <repositories>
                    <repository>
                      <id>central</id>
                      <url>https://repo1.maven.org/maven2</url>
                    </repository>
                    <repository>
                      <id>govpay</id>
                      <url>https://maven.pkg.github.com/govnet-africa/govpay</url>
                      <snapshots>
                          <enabled>true</enabled>
                      </snapshots>
                    </repository>
                    <repository>
                      <id>govnet</id>
                      <url>https://maven.pkg.github.com/govnet-libraries/govbill-java-cli</url>
                      <snapshots>
                          <enabled>true</enabled>
                      </snapshots>
                    </repository>
                </repositories>
              </profile>
          </profiles>

          <servers>
              <server>
                <id>govpay</id>
                <username>${{ secrets.mvn-user }}</username>
                <password>${{ secrets.mvn-token }}</password>
              </server>
              <server>
                <id>govnet</id>
                <username>${{ secrets.mvn-user }}</username>
                <password>${{ secrets.mvn-token }}</password>
              </server>
          </servers>
        </settings>
        EOF
    - name: Build with ${{ inputs.jre-cache }}
      run: |
        rm -rf target && \
        mvn -B package --file pom.xml -DskipTests 
    - name: Write Dockerfile
      env:
        DOCKERFILE_BUILDER_IMG: eclipse-${{ inputs.java-distribution }}:${{ inputs.java-version }}-jdk
        DOCKERFILE_RUNNER_IMG: eclipse-${{ inputs.java-distribution }}:${{ inputs.java-version }}-jre
      run: |
        cat <<EOF > Dockerfile 
        FROM --platform=${{inputs.java-platform}} ${{ env.DOCKERFILE_RUNNER_IMG }}
        WORKDIR /app
        RUN addgroup --system govnet
        RUN adduser --system --ingroup govnet --shell /bin/sh --disabled-password --no-create-home govnet-user
        RUN chown -R govnet-user:govnet /app
        USER govnet-user
        COPY target/*.jar /app/${{ inputs.service }}.jar
        ENV APP_PORT=${{ inputs.service-port }}
        ENV BUILD=${{ env.SERVICE_BUILD }}
        ENV VERSION=${{ inputs.service }}-${{ inputs.version || env.GITHUB_SHA_SHORT }}
        EXPOSE ${{ inputs.service-port }}
        ENTRYPOINT ["java", "-Djava.security.egd=file:/prod/./urandom", "-jar", "/app/${{ inputs.service }}.jar"]
        EOF
    - name: Set docker branch tag
      run: |
        echo "GITHUB_BRANCH_SHORT=`git branch --show-current | sed 's/\//_/g' | tr -d ' '`" >> $GITHUB_ENV
    - name: Build and push docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKERHUB_REPO }}:${{ github.sha }}
          ${{ env.DOCKERHUB_REPO }}:${{ inputs.version || env.GITHUB_SHA_SHORT }}
          ${{ env.DOCKERHUB_REPO }}:latest