env:
  DOCKERFILE_BUILDER_IMG: eclipse-${{ inputs.java-distribution }}:${{ inputs.java-version }}-jdk
  DOCKER_REPO: ${{ vars.DOCKER_ORG }}/${{ vars.DOCKER_REPO }}
  DOCKER_BUILDKIT: 1
on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: null
      java-version:
        required: false
        type: string
        default: "20"
      java-distribution:
        required: false
        type: string
        default: "${{ inputs.java-distribution }}"
      jre-cache:
        required: false
        type: string
        default: "maven"
      service:
        required: true
        type: string
      service-port:
        required: false
        type: number
        default: 8080
      dockerfile-runner-img:
        required: false
        type: string
        default: "eclipse-${{ inputs.java-distribution }}:${{ inputs.java-version }}-jre"
      consul-host:
        required: true
        type: string
      consul-port:
        required: true
        type: number
    secrets:
      mvn-token:
        required: true
      mvn-user:
        required: true
      docker-token:
        required: true
      docker-user:
        required: true
jobs:
  java-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=`git rev-parse --short ${{ github.sha }}`" >> $GITHUB_ENV
          echo "GITHUB_BRANCH_SHORT=`git branch --show-current | sed 's/\//_/g' | tr -d ' '`" >> $GITHUB_ENV
          echo "DOCKER_REPO=${{ vars.DOCKER_ORG }}/$(echo ${{ vars.DOCKER_REPO }} | cut -d '/' -f 2)" >> $GITHUB_ENV
          echo "SERVICE_BUILD=`date -I`-`git rev-parse --short ${{ github.sha }}`" >> $GITHUB_ENV
      - name: Login to Docker Reposotory (${{ inputs.docker-host }})
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker-user }}
          password: ${{ secrets.docker-token }}
      - name: Setup JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          cache: ${{ inputs.jre-cache }}
      - name: Set up Maven settings.xml
        run: |
          cat <<EOF > ~/.m2/settings.xml 
          <?xml version="1.0" encoding="UTF-8"?>
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
            <activeProfiles>
                <activeProfile>github</activeProfile>
            </activeProfiles>
            <profiles>
                <profile>
                  <id>github</id>
                  <repositories>
                      <repository>
                        <id>central</id>
                        <url>https://repo1.maven.org/maven2</url>
                      </repository>
                      <repository>
                        <id>govpay</id>
                        <url>https://maven.pkg.github.com/Instacomm/govpay</url>
                        <snapshots>
                            <enabled>true</enabled>
                        </snapshots>
                      </repository>
                      <repository>
                        <id>instacom</id>
                        <url>https://maven.pkg.github.com/instacom-libraries/govbill-java-cli</url>
                        <snapshots>
                            <enabled>true</enabled>
                        </snapshots>
                      </repository>
                  </repositories>
                </profile>
            </profiles>

            <servers>
                <server>
                  <id>govpay</id>
                  <username>${{ secrets.mvn-user }}</username>
                  <password>${{ secrets.mvn-token }}</password>
                </server>
                <server>
                  <id>instacom</id>
                  <username>${{ secrets.mvn-user }}</username>
                  <password>${{ secrets.mvn-token }}</password>
                </server>
            </servers>
          </settings>
          EOF
      - name: Build with ${{ inputs.jre-cache }}
        run: |
          rm -rf target && \
          mvn -B package --file pom.xml -DskipTests && \
          mkdir -p target/{dependency,extracted} && \
          (cd target/dependency; jar -xf ../*.jar) && \
          java -Djarmode=layertools -jar target/*.jar extract --destination target/extracted
      - name: Write Dockerfile
        env:
          JRE_HOME: /opt/jre
          DOCKERFILE_BUILDER_IMG: eclipse-${{ inputs.java-distribution }}:${{ inputs.java-version }}-jdk
          DOCKERFILE_RUNNER_IMG: eclipse-${{ inputs.java-distribution }}:${{ inputs.java-version }}-jre
        run: |
          cat <<EOF > Dockerfile 
          FROM ${{ env.DOCKERFILE_BUILDER_IMG }} as builder
          USER root
          RUN jlink \
            --module-path "$JAVA_HOME/jmods" \
            --add-modules java.compiler,java.sql,java.naming,java.management,java.instrument,java.rmi,java.desktop,jdk.internal.vm.compiler.management,java.xml.crypto,java.scripting,java.security.jgss,jdk.httpserver,java.net.http,jdk.naming.dns,jdk.crypto.cryptoki,jdk.unsupported \
            --verbose \
            --strip-debug \
            --compress 2 \
            --no-header-files \
            --no-man-pages \
            --output /opt/jre-minimal
          USER app
          WORKDIR /app
          COPY target target
          FROM ${{ env.DOCKERFILE_RUNNER_IMG }}
          VOLUME /tmp
          COPY --from=builder /app/target/extracted/dependencies/ ./
          COPY --from=builder /app/target/extracted/spring-boot-loader/ ./
          COPY --from=builder /app/target/extracted/snapshot-dependencies/ ./
          COPY --from=builder /app/target/extracted/application/ ./
          COPY --from=builder /opt/jre-minimal ${{ env.JRE_HOME }}
          ENV JAVA_HOME=${{ env.JRE_HOME }}
          ENV PATH="$PATH:$JAVA_HOME/bin"
          ENV APP_PORT=${{ inputs.service-port }}
          ENV BUILD=${{ env.SERVICE_BUILD }}
          ENV VERSION=${{ inputs.service }}-${{ inputs.version || env.GITHUB_SHA_SHORT }}
          EXPOSE ${{ inputs.service-port }}
          RUN sed -i 's/\/bin\/ash/\/sbin\/nologin/g' /etc/passwd
          ENTRYPOINT ["${{ env.JRE_HOME }}/bin/java", "-Dspring.cloud.consul.host=${{ inputs.consul-host }}", "-Dspring.cloud.consul.port=${{ inputs.consul-port }}", "org.springframework.boot.loader.JarLauncher"]
          EOF
      - name: Set docker branch tag
        run: |
          echo "GITHUB_BRANCH_SHORT=`git branch --show-current | sed 's/\//_/g' | tr -d ' '`" >> $GITHUB_ENV
      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:${{ github.sha }}
            ${{ env.DOCKER_REPO }}:${{ inputs.version || env.GITHUB_SHA_SHORT }}
            ${{ env.DOCKER_REPO }}:latest
